# Generated by Django 2.2.14 on 2022-04-18 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developver',
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.Developer'),
        ),
    ]
