# Generated by Django 2.2.14 on 2022-04-18 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20220418_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.Project'),
        ),
    ]
