# Generated by Django 2.2.14 on 2022-04-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_developer_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='projects',
        ),
    ]
