# Generated by Django 2.2.14 on 2022-04-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_developer_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.Project'),
        ),
    ]
