# Generated by Django 2.2.14 on 2022-04-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_developer_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='projects',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.Project'),
        ),
    ]
