# Generated by Django 4.0.4 on 2022-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20220418_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='language',
            field=models.TextField(choices=[('1', 'Python'), ('2', 'C++'), ('3', 'Java'), ('4', 'Ruby'), ('5', 'Javascript')], default='1', max_length=50),
        ),
    ]
