# Generated by Django 4.0.4 on 2022-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_developer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='language',
            field=models.TextField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('Ruby', 'Ruby'), ('Javascript', 'Javascript')], default='1', max_length=50),
        ),
    ]
