# Generated by Django 4.0.4 on 2022-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_project_cost_alter_developer_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='language',
            field=models.TextField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('Ruby', 'Ruby'), ('Javascript', 'Javascript'), ('Others', 'Others')], default='1', max_length=50),
        ),
    ]
