# Generated by Django 2.2.20 on 2022-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_developer_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.FloatField(verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='project_id'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
    ]
