# Generated by Django 3.1 on 2022-05-06 11:00

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_auto_20220506_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, verbose_name='cost'),
        ),
    ]
