# Generated by Django 3.1 on 2022-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_auto_20220506_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost_currency',
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.FloatField(verbose_name='cost'),
        ),
    ]
