# Generated by Django 3.1 on 2022-05-06 16:00

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_auto_20220506_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VND')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='cost'),
        ),
    ]
